# CMake generated Testfile for 
# Source directory: /home/darkfell/dev/l3kvg
# Build directory: /home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_engine]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_l3kvg")
set_tests_properties([=[test_engine]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;94;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_fluent]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_fluent_api")
set_tests_properties([=[test_fluent]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;95;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_cypher_ast]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_cypher")
set_tests_properties([=[test_cypher_ast]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;96;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_federation_resolver]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_federation_resolver")
set_tests_properties([=[test_federation_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;97;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_remote]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_remote_client")
set_tests_properties([=[test_remote]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;98;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_coordinator]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_edge_coordinator")
set_tests_properties([=[test_coordinator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;99;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_async]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_async_traversal")
set_tests_properties([=[test_async]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;100;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_edge_props]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_edge_properties")
set_tests_properties([=[test_edge_props]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;101;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_federation]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_federation_id")
set_tests_properties([=[test_federation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;102;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_federation_query]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_federation_query")
set_tests_properties([=[test_federation_query]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;103;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_federation_integration]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_federation_integration")
set_tests_properties([=[test_federation_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;107;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_federation_complex]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_federation_complex")
set_tests_properties([=[test_federation_complex]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;111;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_circuit_breaker]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_circuit_breaker")
set_tests_properties([=[test_circuit_breaker]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;115;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_replication_routing]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_replication_routing")
set_tests_properties([=[test_replication_routing]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;119;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_replication_broadcast]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_replication_broadcast")
set_tests_properties([=[test_replication_broadcast]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;123;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_replication_loop]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_replication_loop")
set_tests_properties([=[test_replication_loop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;127;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_replication_conflict]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_replication_conflict")
set_tests_properties([=[test_replication_conflict]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;131;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_ultimate_mesh]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_ultimate_mesh")
set_tests_properties([=[test_ultimate_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;135;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
add_test([=[test_secure_mesh]=] "/home/darkfell/dev/irods_database_plugin_l3kvg/build_final/l3kvg/test_secure_mesh")
set_tests_properties([=[test_secure_mesh]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/darkfell/dev/l3kvg/CMakeLists.txt;139;add_test;/home/darkfell/dev/l3kvg/CMakeLists.txt;0;")
subdirs("L3KV")
